config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :advance_payments
      resources :currencies
      resources :exchange_rates
      resources :expenses
      resources :groups
      resources :members
      resources :participants
      resources :trips

      root to: "users#index"
    end
  devise_for :users, controllers: {
  registrations: "users/registrations",
  omniauth_callbacks: "users/omniauth_callbacks"
}

  # 認証状態によるトップページ分岐
  authenticated :user do
    root to: "trips#index", as: :authenticated_root
  end

  unauthenticated do
    root to: "homes#index", as: :unauthenticated_root
  end

  # 立替(個別管理, 複数データ)
  resources :groups do
    collection do
      # 旅行作成時の補助API(選択されたグループidを送信)
      post :members_for_group
    end
  end

  resources :trips do
    # 精算画面・処理
    member do
      get :insights
      get :result
      patch :settle
      patch :unsettle
    end

    # 立替(個別管理, 複数データ)
    resources :expenses, only: [ :show, :new, :create, :edit, :update, :destroy ]
    resources :participants, only: [ :show ]
  end

  namespace :share do
    resources :trips, only: [ :show ], param: :share_token do
      member do
        get :insights
        get :result
      end
      resources :expenses, only: [ :show ]
      resources :participants, only: [ :show ]
    end
  end

  # 通貨レート更新用APIエンドポイント
  namespace :api do
    post "fetch_exchange_rate", to: "exchange_rates#fetch"
  end

  get "info", to: "pages#info", as: :info
  get "terms", to: "pages#terms", as: :terms
  get "privacy", to: "pages#privacy", as: :privacy
  get "faq", to: "pages#faq", as: :faq

  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unprocessable_entity", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  # -------------------------------------------------------------------------------------------------
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user

  has_many :trips, dependent: :nullify
  has_many :members, dependent: :destroy

  mount_uploader :icon, GroupIconUploader

  validates :user_id, presence: true
  validates :name, presence: true, length: { maximum: 25, message: "は25字以内で入力してください" }
end

app/controllers/admin/groups_controller.rb
module Admin
  class GroupsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [ :show, :edit, :update, :destroy ]

  def index
    @groups = current_user.groups
  end

  def show
  end

  def new
    @group = current_user.groups.new
    @members_for_form = build_members_for_form([])
  end

  def create
    # グループとメンバー一括作成
    @group = current_user.groups.build(group_params)
    members_name = member_params

    Group.transaction do
      @group.save!
      members_name.each do |mn|
        next if mn[:name].blank?
        @group.members.create!(mn)
      end
    end
    flash[:notice] = I18n.t("flash.group.success.create")
    redirect_to group_path(@group)
  rescue ActiveRecord::RecordInvalid => e
    flash.now[:alert] = I18n.t("flash.group.failed.create")
    @members_for_form = build_members_for_form(member_params)
    render :new, status: :unprocessable_entity
  end


  def edit
    @members_for_form = build_members_for_form(@group.members.map { |gm| { name: gm.name } })
  end

  def update
    Group.transaction do
      @group.update!(group_params)
      @group.members.destroy_all
        member_params.each do |mn|
          next if mn[:name].blank?
          @group.members.create!(mn)
        end
      end
    flash[:notice] = I18n.t("flash.group.success.update")
    redirect_to group_path(@group)

  rescue ActiveRecord::RecordInvalid => e
    flash.now[:alert] = I18n.t("flash.group.failed.update")
    @members_for_form = build_members_for_form(member_params)
    render :edit, status: :unprocessable_entity
  end


  def destroy
    @group.destroy
      redirect_to groups_path, notice: I18n.t("flash.group.success.delete")
  end

  def members_for_group
    group_id = params[:group_id]
    selected_group = current_user.groups.find_by(id: group_id)
    render json: { names: selected_group.members.pluck(:name) }
  end


  private

  def set_group
    @group = current_user.groups.find(params[:id])
  end

  def build_members_for_form(input_members)
    members = input_members.map { |m| @group.members.build(m) }
    (10 - members.size).times { members << @group.members.build }
    members
  end

  def group_params
    params.require(:group).permit(:name, :icon, :remove_icon)
  end

  def member_params
    params.require(:members).map do |m|
      m.permit(:name)
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def file_name(group)
    if group.icon.present?
      File.basename(group.icon.identifier)
    end
  end


  def icon_url(group)
    group.icon&.url || "group-icon.jpg"
  end
end

app/views/groups/_form_card.html.erb
<div class="mx-4 flex flex-col card-style px-4 py-4">
  <%= label_tag "group_name", t('activerecord.attributes.group.name'), class:"font-bold mb-1" %>
  <%= text_field_tag "group[name]", @group.name.present? ? @group.name : nil, id: "group_name", class:"form-style", data:{ "group-validate-target": "groupTitle", "action":"input->group-validate#titleValidate"} %>
  <p class="text-primary-red text-xs pb-0.5" data-group-validate-target="titleErrorMessage"></p>

  <div data-controller="group-icon" data-group-icon-icon-present-value="<%= @group.icon.present? %>" data-group-icon-icon-name-value="<%= file_name(@group) %>"  >
    <p class="font-bold mb-1 mt-2"><%= t('activerecord.attributes.group.icon') %></p>
    <div class="flex items-center justify-between gap-3">
      <div class="flex gap-2">
        <button type="button" class="relative shadow-md hover:bg-neutral-500 py-1 px-2 bg-neutral-600 text-white text-sm rounded-md cursor-pointer">
          <%= t('pages.groups.form_card.select_file') %>
          <%= file_field_tag "group[icon]",accept:"image/*", class:"absolute inset-0 w-full h-full opacity-0", data:{"group-icon-target": "input", action:"change->group-icon#updateFileName"} %>
        </button>
        <p class="text-neutral-400" data-group-icon-target="fileName"></p>
      </div>
      <button type="button" class="hidden w-7 h-7 bg-primary-red shadow-md hover:bg-red-400 rounded-md cursor-pointer px-1" data-group-icon-target="deleteBtn" data-action="click->group-icon#clickDelete">
        <%= inline_svg("svg/cross.svg", class:"text-white")%>
      </button>
      <%= check_box_tag 'group[remove_icon]', '1', false, data: { "group-icon-target": "deleteCheckField" }, class:"hidden"%>

    </div>
  </div>
  
</div>

app/views/groups/edit.html.erb
<% content_for(:title, t('pages.groups.edit.title')) %>

<div class="flex flex-col h-full"
     data-controller="group-validate" 
     data-group-validate-error-messages-value='<%= stimulus_error_messages_json %>' >

  <%# stimulus用フラッシュエラーメッセージ ------------------ %>
  <%= render 'layouts/flash_message/error_for_stimulus' %>
    
  <%# ページ案内 ------------------ %>
  <h1 class="mt-2 my-2 text-xl font-bold text-center"><%= t('pages.groups.edit.title') %></h1>
  
  <%= form_with url: group_path(@group), method: :patch, multipart: true, html:{class:"flex flex-col flex-1 min-h-0", data:{"group-validate-target": "form"}} do %>
    <div class="overflow-y-auto">
      <%= render 'groups/form_card', group: @group %>
      <%= render 'members/form_card', members: @members_for_form %>
    </div>

    <section class="px-4 my-3">
      <div class="separator"></div>
      <div class="w-full flex gap-4">
        <%= link_to t('common.back'), group_path(group: @group), class:"w-1/4 main-action-btn bg-gray-400 text-white dark:bg-neutral-600" %>
        <%= submit_tag t('common.save'), class: "flex-1 main-action-btn bg-primary-blue-100 text-white", data:{"group-validate-target": "submitBtn", action: "click->group-validate#submit click->submit#show"} %>
      </div>
    </section>
  <% end %>

</div>

app/views/groups/index.html.erb
<% content_for(:title, t('pages.groups.index.title')) %>

<%= render 'layouts/modal/groups/group_description' %>

<%# ページ案内 ------------------ %>
<section class="flex items-center relative">
  <%= link_to trips_path(@trips), class:"absolute flex items-center rounded-md shadow-primary h-6 w-10 py-0.5 px-0.5 ml-4 text-white bg-panel-navy dark:text-neutral-700 dark:bg-white" do %>
    <%= inline_svg("svg/navigation-arrow.svg", class:"w-full h-full rotate-180 ")%>
  <% end %>
  <h1 class="mt-2 my-2 text-xl font-bold w-full text-center"><%= t('pages.groups.index.title') %></h1>
  <button type="button" class="absolute right-0 mr-6 h-7 cursor-pointer" data-modal-target="openBtn" data-action="click->modal#openModal" data-modal-name-param="description">
    <%= inline_svg("svg/info.svg", class:"h-full") %>
  </button>
</section>

<%# メインコンテンツ ------------------------------------ %>
<section class="w-full flex-1 min-h-0 overflow-y-auto">
  <%# グループカード ------------------ %>
  <div class="flex-1 flex flex-col gap-4 mx-4 mb-4">
    <% if @groups.present? %>
      <% @groups.each do |group| %>
          <div class="card-style shadow-primary">
            <%= link_to group_path(group), class:"w-full h-full flex gap-4 px-4 py-2 items-center justify-between cursor-pointer" do %>
              <div class="flex items-center gap-2">
                <%= image_tag icon_url(group), alt:"", class:"rounded-full w-10" %>
                <p class="font-bold"><%= group.name %></p>
              </div>
              <%= inline_svg("svg/navigation-arrow.svg", class:"h-5 w-5 text-black text-right dark:text-neutral-500") %>
            <% end %>
          </div>
      <% end %>
    <% else %>
      <%# なければ案内表示 %>
      <div class="flex-1 flex flex-col items-center mt-20 text-center text-neutral-400">
        <%= inline_svg('svg/group2.svg', class:"w-50 py-4")%>
        <p class="text-2xl font-bold"><%= t('pages.groups.index.no_group') %>
          <br>
        <%= t('pages.groups.index.lets_create') %></p>
        <%= inline_svg('svg/navigation-arrow2.svg', class:"w-20 mt-2 animate-bounce")%>
      </div>
    <% end %>
  </div>
</section>

<%# 仕切り線とボタン ------------------ %>
<section class="mx-4 my-3">
  <div class="separator"></div>
  <%= link_to t('pages.groups.index.create_group'), new_group_path, class:"w-full main-action-btn text-neutral-700 bg-action-yellow" %>
</section>

app/views/groups/new.html.erb
<% content_for(:title, t('pages.groups.new.title')) %>

<div class="flex flex-col h-full"
     data-controller="group-validate" 
     data-group-validate-error-messages-value='<%= stimulus_error_messages_json %>' >

  <%# stimulus用フラッシュエラーメッセージ ------------------ %>
  <%= render 'layouts/flash_message/error_for_stimulus' %>
  
  <%# ページ案内 ------------------ %>
  <h1 class="mt-2 my-2 text-xl font-bold text-center"><%= t('pages.groups.new.title') %></h1>

  <%# フォーム & ボタン ------------------ %>
  <%= form_with url: groups_path, multipart: true, html:{class:"flex flex-col flex-1 min-h-0 overflow-y-auto", data:{"group-validate-target": "form"}} do %>

    <%# フォームカード %>
    <section class="overflow-y-auto">
      <%= render 'groups/form_card' %>
      <%= render 'members/form_card', members: @members_for_form %>
    </section>

    <%# ボタン類 %>
    <section class="px-4 my-3">
      <div class="separator"></div>
      <div class="w-full flex gap-4">
        <%# step1時のボタン %>
        <%= link_to t('common.back'), groups_path, class:"w-1/4 main-action-btn bg-gray-400 text-white dark:bg-neutral-600" %>
        <%= submit_tag t('common.save'), class: "flex-1 main-action-btn bg-primary-blue-100 text-white", data:{"group-validate-target": "submitBtn", action: "click->group-validate#submit submit->loading#show"}%>
      </div>
    </section>
  <% end %>
</div>

app/views/groups/show.html.erb
<% content_for(:title, t('pages.groups.show.title')) %>

<%= render 'layouts/modal/groups/destroy' %>

<%# ページ案内 ------------------------------------ %>
<section class="flex items-center relative">
  <%= link_to groups_path, class:"absolute flex items-center rounded-md shadow-primary h-6 w-10 py-0.5 px-0.5 ml-4 text-white bg-panel-navy dark:text-neutral-700 dark:bg-white" do %>
    <%= inline_svg("svg/navigation-arrow.svg", class:"w-full h-full rotate-180 ")%>
  <% end %>
  <h1 class="mt-2 my-2 text-xl font-bold w-full text-center"><%= t('pages.groups.show.title') %></h1>
</section>

<%# メインコンテンツ ------------------------------------ %>
<section class="w-full flex flex-col flex-1 min-h-0 overflow-y-auto">
  <div class="flex-1 mx-4">

    <%# グループ名&編集削除ボタン ------------------ %>
    <div class="flex w-full py-2 px-4 card-style mb-4 justify-between">
      <p class="font-bold text-xl"><%= @group.name %></p>
      <div class="flex pl-5">
        <%= link_to edit_group_path(@group), class:"w-[28px] h-[28px] px-0.5 py-0.5 mx-1 rounded-md bg-panel-navy text-white shadow-primary dark:bg-zinc-600 dark:text-white" do %>
          <%= inline_svg("svg/edit.svg", draggable:"false") %>
        <% end %>
        <%# 削除 %>        
        <button type="button" class="w-[28px] h-[28px] px-0.5 py-0.5 mx-1 rounded-md bg-panel-navy shadow-primary text-white dark:bg-zinc-600 dark:text-white" data-action="click->modal#openModal" data-modal-name-param="destroy">
          <%= inline_svg("svg/delete.svg", draggable:"false") %>
        </button>
      </div>
    </div>

    <%# グループアイコン&グループ情報 --------------- %>
    <div class="flex w-full h-30 gap-4 mb-4 items-center justify-between">
      <div class="h-full shrink-0 card-style p-2">
        <% if @group.icon.present? %>
        <%= image_tag @group.icon.url, alt:"", class: "h-full aspect-square rounded-md" %>
        <% else %>
        <%= image_tag "group-icon.jpg", class: "h-full aspect-square rounded-md" %>
        <% end %>
      </div>
      <div class="h-full card-style flex-1 flex px-4 gap-2 text-neutral-700 items-center">
        <div class="text-left">
          <p class="font-bold"><%= t('pages.groups.show.members_count')%></p>
          <p class="font-bold"><%= t('pages.groups.show.trips_count')%></p>
          <p class="font-bold"><%= t('pages.groups.show.created_at')%></p>
        </div>
        <div >
          <%# 数量&単位表示 %>
          <p><%= @group.members.count %><%= t('pages.groups.show.members_unit')%></p>
          <p><%= @group.trips.count %><%= t('pages.groups.show.trips_unit')%></p>
          <p><%= @group.created_at.year %><%= t('pages.groups.show.created_unit')%></p>
        </div>
      </div>
    </div>

    <%# 参加者カード ----------------- %>
    <div class="flex flex-col card-style" data-controller="accordion">
      <div class="flex justify-between py-2 cursor-pointer" data-accordion-target="bar" data-action="click->accordion#toggle">
        <p class="mx-4 font-bold"><%= t('activerecord.models.member')%></p>
        <%= inline_svg("svg/accordion.svg", class:"w-6 mx-6 transition-transform transform duration-200 text-gray-500", data:{"accordion-target": "icon"}) %>
      </div>  
      <ul class="list-disc text-sm px-8 cursor-pointer h-0 transition-all duration-150 overflow-hidden" data-accordion-target="participantsEl" data-action="click->accordion#toggle">
        <% @group.members.each do |member|%>
        <li class="pb-2"><%= member.name %></li>
        <% end %>
      </ul>
    </div>




    <%# 旅行カード ------------------ %>
    <div class="flex-1 min-h-0 overflow-y-auto flex flex-col my-4">
      <% if @group.trips.present? %>
        <% @group.trips.each do |trip| %>
          <%= link_to trip_path(trip), class:"mb-4", data:{controller:"back", action:"click->back#storeFromPage", "back-return-to-value": "group-show", "back-return-group-id-value": @group.id} do %>
            <%= render 'trips/trip_card', trip: trip, mode: :group %>
          <% end %>
        <% end %> 
      <% else %> 
        <%# なければ案内表示 %>
        <div class="flex-1 flex flex-col items-center text-center text-neutral-400">
          <%= inline_svg('svg/travel-bag.svg', class:"w-40")%>
          <p class="text-2xl font-bold"><%= t('pages.groups.show.no_trip') %></p>
        </div>
      <% end %> 
    </div>

  </div>
</section>


<%# 仕切り線とボタン ------------------ %>
<section class="mx-4 my-3">
  <div class="separator"></div>
  <div class="w-full flex gap-4">
    <%= link_to t('common.back'), groups_path, class:"flex-1 main-action-btn bg-neutral-400 text-white" %> 
  </div>
</section>