config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :advance_payments
      resources :currencies
      resources :exchange_rates
      resources :expenses
      resources :groups
      resources :members
      resources :participants
      resources :trips

      root to: "users#index"
    end
  devise_for :users, controllers: {
  registrations: "users/registrations",
  omniauth_callbacks: "users/omniauth_callbacks"
}

  # 認証状態によるトップページ分岐
  authenticated :user do
    root to: "trips#index", as: :authenticated_root
  end

  unauthenticated do
    root to: "homes#index", as: :unauthenticated_root
  end

  # 立替(個別管理, 複数データ)
  resources :groups do
    collection do
      # 旅行作成時の補助API(選択されたグループidを送信)
      post :members_for_group
    end
  end

  resources :trips do
    # 精算画面・処理
    member do
      get :insights
      get :result
      patch :settle
      patch :unsettle
    end

    # 立替(個別管理, 複数データ)
    resources :expenses, only: [ :show, :new, :create, :edit, :update, :destroy ]
    resources :participants, only: [ :show ]
  end

  namespace :share do
    resources :trips, only: [ :show ], param: :share_token do
      member do
        get :insights
        get :result
      end
      resources :expenses, only: [ :show ]
      resources :participants, only: [ :show ]
    end
  end

  # 通貨レート更新用APIエンドポイント
  namespace :api do
    post "fetch_exchange_rate", to: "exchange_rates#fetch"
  end

  get "info", to: "pages#info", as: :info
  get "terms", to: "pages#terms", as: :terms
  get "privacy", to: "pages#privacy", as: :privacy
  get "faq", to: "pages#faq", as: :faq

  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unprocessable_entity", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  # -------------------------------------------------------------------------------------------------
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  belongs_to :group, optional: true
  belongs_to :currency

  has_many :expenses, dependent: :destroy
  has_many :participants, dependent: :destroy
  accepts_nested_attributes_for :participants, reject_if: :all_blank

  enum settlement_status: { unsettled: 0, settled: 1 }

  validates :user_id, presence: true
  validates :currency_id, presence: true
  validates :title, presence: true, length: { maximum: 25, message: "は25字以内で入力してください" }
  validates :settlement_status, presence: true

  validate :must_have_participant_at_least_one
  validate :participants_within_limit

  before_validation :set_default_currency
  before_validation :set_default_status

  before_create :generate_share_token

  def reset_settlement_status
    self.unsettled! if self.settled?
  end

  def self.ransackable_attributes(auth_object = nil)
    [ "created_at", "departure_date", "group_id", "id", "settlement_status", "title", "updated_at" ]
  end

  private

  def set_default_status
    self.settlement_status ||= :unsettled
  end

  def set_default_currency
    self.currency_id ||= Currency.find_by!(code: "JPY").id
  end

  def must_have_participant_at_least_one
    if participants.reject(&:marked_for_destruction?).empty?
      errors.add(:participants, "参加者を一人以上設定していください")
    end
  end

  def generate_share_token
    self.share_token ||= SecureRandom.urlsafe_base64(15)
  end

  def participants_within_limit
    count = participants.reject(&:marked_for_destruction?).size
    if count > 10
      errors.add(:participants, "は10人までしか追加できません")
    end
  end
end

app/controllers/admin/trips_controller.rb
module Admin
  class TripsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/share/expenses_controller.rb
class Share::ExpensesController < ApplicationController
  skip_before_action :authenticate_user!

  def show
    @trip = Trip.find_by!(share_token: params[:trip_share_token])
    @expense = @trip.expenses.includes(:payer).find(params[:id])
    @owed_participants = @expense.owed_participants
    @advance_payments = @expense.advance_payments.includes(:participant)
  end
end

app/controllers/share/trips_controller.rb
class Share::TripsController < ApplicationController
  skip_before_action :authenticate_user!

  before_action :set_trip

  def show
    @expenses_by_date = @trip.expenses.includes(:payer, :currency).order(payment_date: :asc, created_at: :asc).group_by(&:payment_date)
  end

  def insights
    if @trip.expenses.empty?
       flash.now[:alert] = "精算記録がありません。"
    end
    @balances = BalanceCalculator.new(@trip).balances
    @participants = @trip.participants
  end

  def result
    if @trip.expenses.empty?
      redirect_to share_trip_path(@trip), alert: "精算記録がありません。"
    else
      @settlements = TripDecorator.new(@trip).grouped_settlements
    end
  end

  private

  def set_trip
    @trip = Trip.find_by!(share_token: params[:share_token])
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [ :show, :edit, :update, :destroy, :insights, :result, :settle, :unsettle ]

  def index
    @user_trips = current_user.trips.includes(:currency)
    @q = @user_trips.ransack(params[:q])
    @trips = @q.result(distinct: true).includes(:group).order(departure_date: :desc)
  end

  def show
    @expenses_by_date = @trip.expenses.includes(:payer, :currency).order(payment_date: :asc, created_at: :asc).group_by(&:payment_date)
  end

  def new
    @trip = Trip.new
    10.times { @trip.participants.build }
  end

  def create
    @trip = current_user.trips.build(trip_and_participants_params)
    if @trip.save
      redirect_to trip_path(@trip)
    flash[:notice] = I18n.t("flash.trip.success.create")
    else
      flash.now[:alert] = @trip.errors.full_messages.join("、")
      (10 - @trip.participants.size).times { @trip.participants.build }
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @trip.update(trip_params)
      flash[:notice] = I18n.t("flash.trip.success.update")
      redirect_to trip_path(@trip)
    else
      flash.now[:alert] = @trip.errors.full_messages.join("、")
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @trip.expenses.destroy_all
    @trip.destroy
    redirect_to trips_path, notice: I18n.t("flash.trip.success.delete")
  end


  def insights
    if @trip.expenses.empty?
       flash.now[:alert] = "精算記録がありません。"
    end
    @balances = BalanceCalculator.new(@trip).balances
    @participants = @trip.participants
  end

  def result
    if @trip.expenses.empty?
    redirect_to trip_path(@trip), alert: "精算記録がありません。"
    else
      @settlements = TripDecorator.new(@trip).grouped_settlements
    end
  end

  def settle
    @trip.update(settlement_status: :settled)
    redirect_to trip_path(@trip, settled: true), notice: I18n.t("flash.settle.settled")
  end

  def unsettle
    @trip.update(settlement_status: :unsettled)
    redirect_to trip_path(@trip), notice: I18n.t("flash.settle.unsettled")
  end

  private

  def set_trip
    @trip = current_user.trips.find(params[:id])
  end

  def trip_params
    params.require(:trip).permit(
      :title, :group_id, :departure_date)
  end

  def trip_and_participants_params
    params.require(:trip).permit(
      :title, :group_id, :departure_date, :currency_id,
      participants_attributes: [ :name ]
      )
  end
end

app/helpers/share/expenses_helper.rb
module Share::ExpensesHelper
end

app/helpers/share/trips_helper.rb
module Share::TripsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
  # for_trip_card

  def trip_card_style(mode)
    if [ :index, :group ].include?(mode)
      "shadow-primary"
    else
      "dark:!bg-white shadow-md"
    end
  end

  def show_arrow_icon?(mode)
    [ :index, :group ].include?(mode)
  end

  def can_edit_delete?(mode)
    [ :show ].include?(mode)
  end

  def display_group_info?(mode)
    Rails.logger.debug "mode = #{mode.inspect}"
    [ :index, :show, :share, :result ].include?(mode)
  end

  def group_title_color(mode)
    if [ :index ].include?(mode)
      ""
    else
      "dark:!text-neutral-600"
    end
  end

  def group_icon_url(trip)
     if trip.group&.icon.present?
       trip.group.icon.url
     else
       "group-icon.jpg"
     end
  end

  def group_name(trip)
    trip.group&.name || t("pages.trips.card.temporary_group")
  end


  def settlement_status_options
    Trip.settlement_statuses.map do |key, value|
      [ t("activerecord.attributes.trip.settlement_status.#{key}"), value ]
    end
  end
end

app/views/share/trips/insights.html.erb
<% content_for(:title, "分析") %>

<%= render 'trips/insights_card' %>

app/views/share/trips/result.html.erb
<%#= trip#resultのコピー、パーシャルにするか要検討 %>

<% content_for(:title, "精算結果") %>

<%# ページ案内 ------------------ %>
<section class="flex items-center relative">
  <%= link_to share_trip_path(share_token: @trip.share_token), class:"absolute flex items-center rounded-md shadow-primary h-6 w-10 py-0.5 px-0.5 ml-4 bg-panel-navy dark:bg-neutral-800" do %>
    <%= inline_svg("svg/navigation-arrow.svg", class:"w-full h-full rotate-180 text-white dark:text-neutral-300")%>
  <% end %>
  <h1 class="mt-2 my-2 text-xl font-bold w-full text-center">精算結果</h1>
</section>

<section class="flex-1 overflow-y-auto min-h-0">
  <div class="flex-1 mx-4">
    <%# 旅行カード ------------------ %>
    <%= render 'trips/trip_card', trip: @trip, mode: :result %>

    <%# サブタイトル ------------------ %>
    <h2 class="mx-2 my-1.5 font-bold mt-2">支払・受取リスト</h2>

    <%# 精算カード ------------------ %>
    <div class="flex flex-col gap-4">
      <% @settlements.each do |s| %>
        <%= render 'trips/result_card', settlement: s %>
      <% end %>
    </div> 

  </div>
</section>

<%# 仕切り線とボタン ------------------ %>
<div class="px-4 my-3">
  <div class="separator"></div>
  <%= link_to "戻る", share_trip_path(share_token: @trip.share_token), class:"w-full flex main-action-btn bg-gray-400 text-white dark:bg-neutral-600" %>
</div>

app/views/share/trips/show.html.erb
<% content_for(:title, "旅行詳細[共有]") %>

<%= render 'layouts/modal/trips/share_description' %>

<%# ページ案内 ------------------------------------ %>
<section class="flex items-center relative">
  <h1 class="mt-2 my-2 text-xl font-bold w-full text-center">旅行詳細</h1>
</section>

<%# メインコンテンツ ------------------------------------ %>
<section class="w-full overflow-y-auto">
  <div class="mx-4">

    <%# 旅行カード ------------------ %>
    <%= render 'trips/trip_card', trip: @trip, mode: :share %>

    <%# 共有&グラフページボタン ------- %>
    <div class="w-full my-4 flex gap-4" data-controller="copy-trip-token">
      
      <div class="flex flex-1 card-style h-10 items-center justify-between px-2">
        <%# 共有リンク %>
        <button class="py-0.5 bg-neutral-400 hover:bg-panel-navy active:bg-panel-navy rounded-l-md text-sm text-white px-1"
                data-action="click->copy-trip-token#copyToken">COPY</button>
        <input class="py-0.5 text-sm flex-1 bg-neutral-100 rounded-r-md px-2 dark:text-white dark:bg-neutral-700" data-copy-trip-token-target="tokenInput" id="share_link" value= "<%= share_trip_url(@trip.share_token) %>" readonly>
        <%# 共有機能info %>
        <button type="button" class="h-6 ml-1 cursor-pointer" data-action="click->modal#openModal" data-modal-name-param="description">
          <%= inline_svg("svg/info.svg", class:"h-full") %>
        </button>
      </div>

      <%# グラフページボタン %>
      <div class="gap-2 w-1/5 card-style h-10 cursor-pointer">
        <%= link_to insights_share_trip_path(share_token: @trip.share_token),  class:"flex h-full w-full items-center justify-center" do %>
          <%= inline_svg("svg/graph.svg", class:"h-6") %>
        <% end %>
      </div>

    </div>

    <%# 参加者カード ----------------- %>
    <div class="mt-2 flex flex-col card-style" data-controller="accordion">
      <div class="flex justify-between py-2 cursor-pointer" data-accordion-target="bar" data-action="click->accordion#toggle">
        <p class="mx-4 font-bold">参加者</p>
        <%= inline_svg("svg/accordion.svg", class:"w-6 mx-6 transition-transform transform duration-200 text-gray-500", data:{"accordion-target": "icon"}) %>
      </div>  
      <ul class="list-disc text-sm px-8 cursor-pointer h-0 transition-all duration-150 overflow-hidden" data-accordion-target="participantsEl" data-action="click->accordion#toggle">
        <% @trip.participants.each do |participant|%>
        <li class="pb-2"><%= participant.name %></li>
        <% end %>
      </ul>
    </div>

    <%# 立替カード一覧 ------------------ %>
    <div class="flex-1 flex flex-col pb-2">
      <% @expenses_by_date.each do |date, expense|%>
        <div class="mt-2 font-bold px-2"><%= date.strftime("%m/%d") %></div>
          <div class="flex flex-col gap-4">
            <% expense.each do |e| %>
                <%= link_to share_trip_expense_path(trip_share_token: @trip.share_token, id: e.id) do %>
                  <%= render 'expenses/expense_card', expense: e %>
                <% end %>
            <% end %>
          </div>
      <% end %>
    </div>

  </div>
</section>

<%# 仕切り線とボタン ------------------ %>
<% if @expenses.present?%>
  <section class="px-4 my-3">
    <div class="separator"></div>
    <%= link_to "精算結果", result_share_trip_path(share_token: @trip.share_token), class:"w-full flex main-action-btn bg-primary-red text-white" %>  
  </section>
<% end %>